firstname = input("Enter first name:")
lastname = input("Enter last name :")
middlename = input("Enter middle name:") 
birthday = input("Enter birthday:")
gender = input("Enter gender:")
address = input("Enter address:")
course = input("Enter course:")
yearlevel = input("Enter year level:")
print("\nFirst Name:",firstname) 
print("Last Name:",lastname) 
print("Middle Name:",middlename)
print("Birthday:",birthday)
print("Gender:",gender)
print("Address:",address)
print("Course:",course)
print("Year Level:",yearlevel)
